# Generated by Django 3.0.3 on 2020-05-14 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='Titulo para a exibição')),
                ('descricao', models.TextField(null=True, verbose_name='Lista de benefícios')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='Titulo para a exibição')),
                ('descricao', models.TextField(max_length=100, null=True, verbose_name='Descrição do evento')),
                ('imagem', models.ImageField(null=True, upload_to='eventos/', verbose_name='Imagem do evento')),
                ('evento', models.TextField(null=True, verbose_name='Descrição na página do evento')),
                ('local', models.CharField(max_length=100, null=True, verbose_name='Local do evento')),
                ('slug', models.SlugField(null=True, verbose_name='Atalho na URL')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do evento')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='Titulo para a exibição')),
                ('imagem', models.ImageField(null=True, upload_to='home/', verbose_name='Imagem de fundo do banner inicial')),
            ],
            options={
                'verbose_name': 'Banner inicial',
                'verbose_name_plural': 'Banner inicial',
            },
        ),
        migrations.CreateModel(
            name='Quemsomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='Titulo para a exibição')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição de quem somos')),
                ('missao', models.TextField(null=True, verbose_name='Missão')),
                ('visao', models.TextField(null=True, verbose_name='Visão')),
                ('valores', models.TextField(null=True, verbose_name='Valores')),
            ],
            options={
                'verbose_name': 'Quem Somos',
                'verbose_name_plural': 'Quem Somos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='Titulo para a exibição')),
                ('eventoshoteis', models.TextField(null=True, verbose_name='Eventos e hotéis')),
                ('alimentosebebidas', models.TextField(null=True, verbose_name='Alimentos e bebidas')),
                ('transporte', models.TextField(null=True, verbose_name='Transporte')),
                ('outrosservicos', models.TextField(null=True, verbose_name='Outros serviços')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
