# Generated by Django 3.0.3 on 2020-05-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('descricao', models.TextField(verbose_name='descrição de quem somos')),
            ],
            options={
                'verbose_name': 'Conheça Natal',
                'verbose_name_plural': 'Conheça Natal',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='imagem',
            field=models.ImageField(null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
    ]
