# Generated by Django 3.0.3 on 2020-05-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200505_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('instagram', models.CharField(max_length=30, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=30, verbose_name='Facebook')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('twitter', models.CharField(max_length=30, verbose_name='Twitter')),
            ],
        ),
    ]
