# Generated by Django 3.0.3 on 2020-05-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contatos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatos',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='missao',
            options={'verbose_name': 'Missão', 'verbose_name_plural': 'Missão'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Quem Somos', 'verbose_name_plural': 'Quem Somos'},
        ),
        migrations.AlterModelOptions(
            name='valores',
            options={'verbose_name': 'Valores', 'verbose_name_plural': 'Valores'},
        ),
        migrations.AlterModelOptions(
            name='visao',
            options={'verbose_name': 'Visão', 'verbose_name_plural': 'Visão'},
        ),
        migrations.AlterField(
            model_name='beneficios',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AlterField(
            model_name='card',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AlterField(
            model_name='visao',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='de um titulo para a etiqueta'),
        ),
    ]
