# Generated by Django 3.0.3 on 2020-05-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200505_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pagina',
            field=models.TextField(null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AlterField(
            model_name='card',
            name='descricao',
            field=models.TextField(max_length=100, verbose_name='descrição do evento'),
        ),
    ]
