# Generated by Django 3.0.3 on 2020-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200510_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imagem',
            new_name='imagemum',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='pagina',
            new_name='paginaum',
        ),
        migrations.RemoveField(
            model_name='card',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='card',
            name='titulo',
        ),
        migrations.AddField(
            model_name='card',
            name='carrosel',
            field=models.CharField(max_length=30, null=True, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AddField(
            model_name='card',
            name='descricaodo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='descricaotre',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='descricaoum',
            field=models.TextField(max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='imagemdo',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='imagemtre',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='paginado',
            field=models.TextField(blank=True, null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='paginatre',
            field=models.TextField(blank=True, null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='titulodo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='titulotre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='tituloum',
            field=models.CharField(max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
    ]
