# Generated by Django 3.0.3 on 2020-05-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200510_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descricaoum',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='imagemum',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='paginaum',
            new_name='pagina',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='carrosel',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='descricaodo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='descricaotre',
        ),
        migrations.RemoveField(
            model_name='card',
            name='imagemdo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='imagemtre',
        ),
        migrations.RemoveField(
            model_name='card',
            name='paginado',
        ),
        migrations.RemoveField(
            model_name='card',
            name='paginatre',
        ),
        migrations.RemoveField(
            model_name='card',
            name='titulodo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='titulotre',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tituloum',
        ),
    ]
