# Generated by Django 3.0.3 on 2020-05-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200510_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cards',
        ),
    ]
