# Generated by Django 3.0.3 on 2020-05-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200510_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
