# Generated by Django 3.0.3 on 2020-05-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='carrosel',
            field=models.CharField(max_length=30, null=True, verbose_name='de um titulo para a etiqueta'),
        ),
        migrations.AddField(
            model_name='card',
            name='descricaodo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='descricaotre',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='imagemdo',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='imagemtre',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='paginado',
            field=models.TextField(blank=True, null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='paginatre',
            field=models.TextField(blank=True, null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='titulodo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
        migrations.AddField(
            model_name='card',
            name='titulotre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
        migrations.AlterField(
            model_name='card',
            name='titulo',
            field=models.CharField(max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
    ]
