# Generated by Django 3.0.3 on 2020-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200510_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardsdois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrosel', models.CharField(max_length=30, null=True, verbose_name='de um titulo para a etiqueta')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='de um titulo para o evento')),
                ('descricao', models.TextField(max_length=100, null=True, verbose_name='descrição do evento')),
                ('imagem', models.ImageField(null=True, upload_to='eventos/', verbose_name='imagem do evento')),
                ('pagina', models.TextField(null=True, verbose_name='descrição na página do evento')),
                ('titulodo', models.CharField(blank=True, max_length=30, null=True, verbose_name='de um titulo para o evento')),
                ('descricaodo', models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição do evento')),
                ('imagemdo', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='imagem do evento')),
                ('paginado', models.TextField(blank=True, null=True, verbose_name='descrição na página do evento')),
            ],
        ),
        migrations.CreateModel(
            name='Cardsum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrosel', models.CharField(max_length=30, null=True, verbose_name='de um titulo para a etiqueta')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='de um titulo para o evento')),
                ('descricao', models.TextField(max_length=100, null=True, verbose_name='descrição do evento')),
                ('imagem', models.ImageField(null=True, upload_to='eventos/', verbose_name='imagem do evento')),
                ('pagina', models.TextField(null=True, verbose_name='descrição na página do evento')),
            ],
            options={
                'verbose_name': 'Demais carroseis',
                'verbose_name_plural': 'Demais carroseis',
            },
        ),
    ]
