# Generated by Django 3.0.3 on 2020-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_cardsdois_cardsum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Carroseis com tres eventos', 'verbose_name_plural': 'Carroseis com tres eventos'},
        ),
        migrations.AlterModelOptions(
            name='cardsdois',
            options={'verbose_name': 'Carrosseis com dois eventos', 'verbose_name_plural': 'Carrosseis com dois eventos'},
        ),
        migrations.AlterModelOptions(
            name='cardsum',
            options={'verbose_name': 'Carrosel com um evento', 'verbose_name_plural': 'Carrosel com um evento'},
        ),
        migrations.AlterField(
            model_name='cards',
            name='descricaodo',
            field=models.TextField(max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='descricaotre',
            field=models.TextField(max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='imagemdo',
            field=models.ImageField(null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='imagemtre',
            field=models.ImageField(null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='paginado',
            field=models.TextField(null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='paginatre',
            field=models.TextField(null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='titulodo',
            field=models.CharField(max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='titulotre',
            field=models.CharField(max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
        migrations.AlterField(
            model_name='cardsdois',
            name='descricaodo',
            field=models.TextField(max_length=100, null=True, verbose_name='descrição do evento'),
        ),
        migrations.AlterField(
            model_name='cardsdois',
            name='imagemdo',
            field=models.ImageField(null=True, upload_to='eventos/', verbose_name='imagem do evento'),
        ),
        migrations.AlterField(
            model_name='cardsdois',
            name='paginado',
            field=models.TextField(null=True, verbose_name='descrição na página do evento'),
        ),
        migrations.AlterField(
            model_name='cardsdois',
            name='titulodo',
            field=models.CharField(max_length=30, null=True, verbose_name='de um titulo para o evento'),
        ),
    ]
